default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog
  username: <%= ENV['BLOG_DATABASE_USERNAME'] %>
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
