# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 569de20ccaccab9ce96d47d096cdbfc6a5f73bc039e095b3aea00ef16fcc87969077b44964481a1f288d8a90549440989aa7761f4d723b1d570e402f949bde0f

test:
  secret_key_base: 39535fe9e6abe315bc687ba0c4c0a9d6a7fb466f4c274860ed58c6a256b0cd4de9dffe10eaa43978764267365ea2ba998271494998a2b9168fb3807139e018d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
